name: Build and Test React Application-CI

# Controls when the action will run
on:
  # Trigger on the events
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Test Building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request from Develop to Testing-Build
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          source_branch: develop
          target_branch: testing-build
          title: Auto Pull Request Develop to Testing-Build Branch
          old-string: This PR was automatically created from the develop branch to test build the files
          template: .github/PULL_REQUEST_TEMPLATE/FEATURE.md
